version: "3.8"
services:
  # front-end:
  #   image: tonyyou998/roomus-fe
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - uit
  #   depends_on:
  #     - roomusDb
  #   deploy: 
  #     restart_policy:
  #         condition: on-failure
  #         delay: 3s
  #         max_attempts: 3
  #         window: 120s
  backend:
    image: tonyyou998/roomus-be
    ports:
      - "3001:3001"
    # networks:
    #   - uit
    environment:
      - JWT_KEY=vh5iz1VsJeciZ8TA
    deploy: 
      restart_policy:
          condition: on-failure
          delay: 3s
          max_attempts: 3
          window: 120s
  # roomusDb:
  #   image: mysql:8.0
  #   restart: always
  #   env_file: ./.env
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
  #     - MYSQL_DATABASE=$DB_NAME
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - roomusDb:/var/lib/mysql
  #   networks:
  #     - uit

# volumes:
#   roomusDb:
# networks:
#   uit:
#     driver: bridge
